##' Perform posterior predictive simulations.
##'
##' This function performs posterior predictive simulations. The simulations can be used to check if the model and parameter estimates can generate data that is close to your data. This is a measure of model adequacy. We expect the most adequate model to generate data is closer to the observed data than the alternative models. After simulating a large number of datasets you can use a series of summary statistics to check how close the simulated data is to the observed data. Check the examples.
##' @title Make posterior predictive simulations.
##' @param out The 'out' file from the MCMC function.
##' @param mcmc.chain The posterior chain generated by 'read.single.R.iwish' or 'read.multi.R.iwish'.
##' @param mc.cores The number of cores to be used for parallel simulations. Optional argument. Default is 'NULL' and uses a single computer processor. Will import 'parallel' if provided with a number of cores.
##' @return A list of matrices. Each element is a simulation of datasets. Using the same model and parameter estimates from the joint posterior distribution.
##' @export
##' @seealso \code{read.single.R.iwish} or \code{read.multi.R.iwish}
##' @importFrom phytools sim.corrs
postPredicSims <- function(out, mcmc.chain, mc.cores=NULL){
    root <- mcmc.chain[[1]]
    lchain <- dim(root)[1]
    if( out$p == 1 ){
        R <- mcmc.chain[[2]]
    } else {
        R <- list()
        for(i in 1:lchain){
            R[[i]] <- lapply(1:out$p, function(x) mcmc.chain[[2]][[x]][[i]] )
            names(R[[i]]) <- colnames(out$phy$mapped.edge)
        }
    }
    if( is.null(mc.cores) ){
        sim.data <- lapply(1:lchain, function(x) sim.corrs(tree = out$phy, vcv = R[[x]], anc = root[x,]) )
    } else {
        if( is.numeric(mc.cores) ){
            library(parallel)
            sim.data <- mclapply(1:lchain, function(x) sim.corrs(tree = out$phy, vcv = R[[x]], anc = root[x,])
                               , mc.cores=mc.cores )
        } else {
            stop("mc.cores needs to be NULL or the number of cores to be used for 'mclapply'")
        }
    }

    return(sim.data)
}
