# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by three
#'
#' @param x A single integer.
#' @export
timesThree <- function(x) {
    .Call('_ratematrix_timesThree', PACKAGE = 'ratematrix', x)
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('_ratematrix_timesTwo', PACKAGE = 'ratematrix', x)
}

